### PR TITLE
Add developer docs for the semantic stage

### LINKED ISSUE #1296: Can't assign the results of a map
### Describe the bug
Although there is code in pyccel to do this, it is not tested and has therefore become out of date and stopped working. Furthermore, it is bad practice to save an iterable to a variable as it cannot be used more than once.

### To Reproduce
Provide code to reproduce the behaviour:
```python
@types( 'int[:]' )
def return_map_on_1d_array( z ):
    import numpy as np

    @types( int )
    def f( x ):
        return x+5

    x = map(f,z)
    
    return np.array(x)
```

### Error details
The first error is:
```bash/fortran/c
>               name = str(rhs.args[0])
E               AttributeError: 'PythonMap' object has no attribute 'args'
```

### To fix

The code should either be removed or modified to accept `list(map(f,z))`

### PR DESCRIPTION
**Pull request by EmilyBourne**
Add developer docs for the semantic stage. Correct typos in function names in the `SemanticParser`. Delete some dead code. Fix #1296 .

As this is the most complicated and important stage in the pyccel pipeline it is likely that I may have forgotten something which needs to be explained. Please let me know if you see anything

### CODE REVIEW

File: developer_docs/semantic_stage.md [hunk 1]
```diff
@@ -0,0 +1,180 @@
...
+The semantic stage serves several purposes:
+1.  [**Types**](#Types) : Determine the type of each symbol
+2.  [**Impose Restrictions**](#Impose-restrictions) : Ensure that the code follows any restictions that Pyccel imposes
+3.  [**Function Recognition**](#Function-recognition) : Identify any functions that are recognised by Pyccel
+4.  [**Imports**](#Imports) : Identify imports
+5.  [**Low-level Objects**](#Low-level-objects) : Create any objects which are hidden in high-level code, but must appear explicitly in low-level code
+6.  [**Object Tree**](#Object-tree) : Ensure the object tree is correctly constructed
+7.  [**Name Collisions**](#Name-collisions) : Ensure any potential name collisions are avoided
+
+## Navigation
```
Comment (AbdelkhalekBAROUDI) [inline developer_docs/semantic_stage.md:14]: This subsection is not enumerated above in the several purposes.

Comment (EmilyBourne) [reply developer_docs/semantic_stage.md:14]: I don't consider navigation to be a purpose. The list above details the aims of the files not the following sections.  Do you think this section needs to be mentioned beforehand?

File: developer_docs/semantic_stage.md [hunk 2]
```diff
@@ -0,0 +1,180 @@
...
+Otherwise the object will be created in the `SemanticParser._handle_function` function and its type will be determined by its constructor.
+
+## Imports
+
+In order for the semantic parser to have all information necessary for the different steps, imports must be handled correctly.
+In the case of user-defined modules the imported file must have also been parsed.
+The class [pyccel.parser.parser.Parser](../pyccel/parser/parser.py) ensures that functions are parsed in the correct order so that the information is available.
+In the `_visit_Import` function, the [`pyccel.ast.core.Module`](../pyccel/ast/core.py) object representing the imported file is therefore available.
+This object contains all necessary `FunctionDef`, `Variable` and `ClassDef` objects which may be imported.
+Thse are then placed into the `Scope.imports` dictionary so they can be recognised when they are used in the file.
```
Comment (jalalium) [inline developer_docs/semantic_stage.md:122]: small typo here `thse`

File: developer_docs/semantic_stage.md [hunk 3]
```diff
@@ -0,0 +1,180 @@
...
+In order to avoid problems arising from forgetfulness we try to add additional objects in the most general place possible.
+For example, allocation occurs in the function `SemanticParser._assign_lhs_variable`.
+Variable declarations are created in the printer when needed from the scope variables (this allows each language to place the decorators in the most appropriate location).
+
+## Object Tree
+
+All the objects in the Pyccel AST inherit from [`pyccel.ast.basic.Basic`](../pyccel/ast/basic.py).
+This super-class stores information about how the various objects are related.
+This allows the class to provide functions such as `get_user_nodes`, `get_attribute_nodes`, `is_attribute_of`, `is_user_of`, and `substitute`.
+
```
Comment (jalalium) [inline developer_docs/semantic_stage.md:159]: I think these functions need more explaining please.

File: developer_docs/semantic_stage.md [hunk 4]
```diff
@@ -0,0 +1,180 @@
...
+The tree is constructed in `Basic.__init__` using the `_attribute_nodes` attribute to recognise the names of attributes which must be added to the tree.
+Nevertheless the object tree should be considered in two situations.
+Firstly, if the object is constructed and AST objects are then added to it (e.g. the member function `pyccel.ast.core.CodeBlock.insert2body` used for the garbage collector).
+In this case the new object does not pass through the constructor of its user.
+It is therefore important to call `set_current_user_node` on the new object to update the tree.
+Secondly, if the object contains all necessary information after the syntactic stage (e.g. `pyccel.ast.core.Continue`) we may be tempted to return the object as is.
+However if this were done there would be multiple user nodes from both the semantic and the syntactic stage.
```
Comment (jalalium) [inline developer_docs/semantic_stage.md:166]: I did not get this point

**Review by jalalium — APPROVED** [review]
Excellent work!

File: developer_docs/semantic_stage.md (hunk 1 above)
Comment (AbdelkhalekBAROUDI) [reply developer_docs/semantic_stage.md:14]: I thought that you forgot to mention it in the list since it has the same structure as the purposes.

Comment (EmilyBourne) [reply developer_docs/semantic_stage.md:14]: Ok. Do you think it needs to be mentioned? Or are you happy to resolve this conversation

File: developer_docs/semantic_stage.md (hunk 2 above)
Comment (EmilyBourne) [reply developer_docs/semantic_stage.md]: Fixed [fa2551e](https://github.com/pyccel/pyccel/pull/1294/commits/fa2551e44760e3666233c8968341542ab86204fa)

File: developer_docs/semantic_stage.md (hunk 3 above)
Comment (EmilyBourne) [reply developer_docs/semantic_stage.md:160]: Fixed [1b9f8e5](https://github.com/pyccel/pyccel/pull/1294/commits/1b9f8e585947fb6a5ab66dc6049c6fdc55b4b5d9)

File: developer_docs/semantic_stage.md (hunk 1 above)
Comment (AbdelkhalekBAROUDI) [reply developer_docs/semantic_stage.md:14]: I'm happy to resolve it. Excellent work tough !!

**Review by AbdelkhalekBAROUDI — APPROVED** [review]

File: developer_docs/semantic_stage.md [hunk 5]
```diff
@@ -0,0 +1,184 @@
...
+Additional objects can often appear in awkward places where they cannot be easily returned as a `CodeBlock`.
+This is the case for example if the object is needed to properly define something inside the right hand side of an `Assign`.
+As the right hand side of an Assign cannot be a `CodeBlock` the additional expressions must be collected outside the usual flow.
+The attribute `SemanticParser._additional_exprs` exists to hold these expressions.
+This object is a list of lists which is initialised and inserted in `_visit_CodeBlock`.
+A list of lists is necessary in case a `CodeBlock` can be found inside another (e.g. `a = [i for i in range]` where a `CodeBlock` contains the `Assign`, but another exists inside the `For` loop).
+
+In order to avoid problems arising from forgetfulness we try to add additional objects in the most general place possible.
+For example, allocation occurs in the function `SemanticParser._assign_lhs_variable`.
+Variable declarations are created in the printer when needed from the scope variables (this allows each language to place the decorators in the most appropriate location).
```
Comment (yguclu) [inline developer_docs/semantic_stage.md:152]: Typo: decorators -> declarations

File: developer_docs/semantic_stage.md [hunk 6]
```diff
@@ -0,0 +1,184 @@
...
+
+## Object Tree
+
+All the objects in the Pyccel AST inherit from [`pyccel.ast.basic.Basic`](../pyccel/ast/basic.py).
+This super-class stores information about how the various objects are related.
+This allows the class to provide functions such as `get_user_nodes` (which returns all objects of a given type which use the node), `get_attribute_nodes` (which returns all objects of a given type which are used by the node), `is_attribute_of` (which indicates if the argument is used by the node), `is_user_of` (which indicates if the argument uses the node), and `substitute` (which allows all occurrences of an object in the node to be replaced by a different object).
```
Comment (yguclu) [inline developer_docs/semantic_stage.md:158]: I think there is a mistake here:

- `self.is_attribute_of(arg)` indicates if the node `self` is used by the argument `arg`
- `self.is_user_of(arg)` indicates if the node `self` uses the argument `arg`

Your description says the opposite.

File: developer_docs/semantic_stage.md [hunk 7]
```diff
@@ -0,0 +1,184 @@
...
+In this case the new object does not pass through the constructor of its user.
+It is therefore important to call `set_current_user_node` on the new object to update the tree.
+Secondly, if the object contains all necessary information after the syntactic stage (e.g. `pyccel.ast.core.Continue`) we may be tempted to return the object as is.
+However if this were done there would be multiple user nodes from both the semantic and the syntactic stage.
+For example, if we need to have access to the containing function we could do `expr.get_user_nodes(FunctionDef)`.
+We expect that this only returns semantic objects if `expr` is a result of the semantic stage.
+However if objects such as `pyccel.ast.core.Continue` are returned as is, then we would get access to both the syntactic and the semantic versions of the containing function without any way to distinguish between the two.
+To avoid this it is important to call the `pyccel.ast.basic.Basic.clear_user_nodes` function to remove the syntactic objects from the tree.
```
Comment (yguclu) [inline developer_docs/semantic_stage.md:171]: When exactly should this function be called?

File: developer_docs/semantic_stage.md [hunk 8]
```diff
@@ -0,0 +1,184 @@
...
+    -   _warning_ : An error will be printed but Pyccel will continue executing
+    -   _error_ : An error will be printed but Pyccel will continue executing the syntactic stage
+    -   _fatal_ : An error will be printed and Pyccel will stop executing. This is the level used the most frequently in the semantic stage as, if information such as the type cannot be determined, the object cannot be created which will cause problems later in the execution.
+
+It should be noted that Pyccel assumes that the user has provided valid code.
+It is not feasible to provide error messages for every possible coding error so we limit ourselves to simple validity checks and Pyccel restriction errors.
+
+## Function Recognition
+
+Function calls are split into two groups which are handled in different ways.
```
Comment (yguclu) [inline developer_docs/semantic_stage.md:99]: After the syntactic stage, are all function calls represented as `FunctionCall` nodes?

**Review by yguclu — CHANGES_REQUESTED** [review]
Impressive effort! I have just a few comments

File: developer_docs/semantic_stage.md (hunk 8 above)
Comment (EmilyBourne) [reply developer_docs/semantic_stage.md:99]: Yes

Comment (yguclu) [reply developer_docs/semantic_stage.md:99]: Then I think it is worth emphasizing this!

The `expr` node is always a `FunctionCall` object, and the corresponding function definition is always contained in `expr.funcdef`. Depending on the type of this attribute, the call is handled in different ways by `visit_FunctionCall`.

File: developer_docs/semantic_stage.md (hunk 7 above)
Comment (EmilyBourne) [reply developer_docs/semantic_stage.md]: a41dce79

File: developer_docs/semantic_stage.md (hunk 6 above)
Comment (EmilyBourne) [reply developer_docs/semantic_stage.md]: Fixed 9b7f3758

File: developer_docs/semantic_stage.md (hunk 5 above)
Comment (EmilyBourne) [reply developer_docs/semantic_stage.md]: Fixed 3c20d9dd

File: developer_docs/semantic_stage.md [hunk 9]
```diff
@@ -0,0 +1,184 @@
...
+            return 1.0, False
+        elif b:
+            return 10, 4j
+        elif a:
+            return True
+        else:
+            return
+    ```
+
+3.  A conscious choice has been made to not support code as there is no way to obtain a performant translation.
```
[the remark this answers is not in the document]
Comment (EmilyBourne) [reply developer_docs/semantic_stage.md]: Fixed 088fd279

File: developer_docs/semantic_stage.md [hunk 10]
```diff
@@ -0,0 +1,184 @@
...
+This function takes several arguments (see docstring for more details).
+The most important arguments are:
+-   _message_ : Describe the issue that lead to the error
+
+-   _symbol_ : The Python AST object should be passed here. This object contains information about its position in the file (line number, column) which ensures the user can more easily locate their error
+
+-   _severity_ : The severity level must be one of the following:
+    -   _warning_ : An error will be printed but Pyccel will continue executing
+    -   _error_ : An error will be printed but Pyccel will continue executing the syntactic stage
+    -   _fatal_ : An error will be printed and Pyccel will stop executing. This is the level used the most frequently in the semantic stage as, if information such as the type cannot be determined, the object cannot be created which will cause problems later in the execution.
```
[the remark this answers is not in the document]
Comment (EmilyBourne) [reply developer_docs/semantic_stage.md]: Fixed 87c42ed1

File: developer_docs/semantic_stage.md [hunk 11]
```diff
@@ -0,0 +1,184 @@
...
+Where possible this should be done by accessing the `Errors()` singleton and calling the `report` function.
+This function takes several arguments (see docstring for more details).
+The most important arguments are:
+-   _message_ : Describe the issue that lead to the error
+
+-   _symbol_ : The Python AST object should be passed here. This object contains information about its position in the file (line number, column) which ensures the user can more easily locate their error
+
+-   _severity_ : The severity level must be one of the following:
+    -   _warning_ : An error will be printed but Pyccel will continue executing
+    -   _error_ : An error will be printed but Pyccel will continue executing the syntactic stage
```
[the remark this answers is not in the document]
Comment (EmilyBourne) [reply developer_docs/semantic_stage.md]: Fixed 87c42ed1

File: developer_docs/semantic_stage.md (hunk 8 above)
Comment (EmilyBourne) [reply developer_docs/semantic_stage.md]: Having double-checked this it seems that there is one exception (`print`). I have described this here : 6443555d
I suspect the different treatment of `print` comes from a time when python 2 was parsed but I'm not sure. I don't see any reason for the different treatment at the moment. It would be better to open a small PR to remove this special treatment

Comment (yguclu) [reply developer_docs/semantic_stage.md]: You are correct, originally Pyccel wanted to support Python 2 and 3. I agree with your suggestion: Python 3 `print` is a built-in function like all the others, so we should remove this special treatment.

File: developer_docs/semantic_stage.md [hunk 12]
```diff
@@ -0,0 +1,198 @@
...
+We expect that this only returns semantic objects if `expr` is a result of the semantic stage.
+However if objects such as `pyccel.ast.core.Continue` are returned as is, then we would get access to both the syntactic and the semantic versions of the containing function without any way to distinguish between the two.
+To avoid this it is important to call the `pyccel.ast.basic.Basic.clear_user_nodes` function to remove the syntactic objects from the tree before returning the object:
+```python
+def _visit_Continue(self, expr):
+    expr.clear_user_nodes()
+    return expr
+```
+
+BEWARE: Doing this invalidates the old AST from the syntactic stage so this AST must not be reused after the semantic stage.
```
Comment (yguclu) [inline developer_docs/semantic_stage.md:185]: Thanks for the clarification!

**Review by yguclu — APPROVED** [review]
