### ISSUE TITLE
Can't assign the results of a map

### ISSUE THREAD

**Issue by EmilyBourne** [pyccel/pyccel#1296]
### Describe the bug
Although there is code in pyccel to do this, it is not tested and has therefore become out of date and stopped working. Furthermore, it is bad practice to save an iterable to a variable as it cannot be used more than once.

### To Reproduce
Provide code to reproduce the behaviour:
```python
@types( 'int[:]' )
def return_map_on_1d_array( z ):
    import numpy as np

    @types( int )
    def f( x ):
        return x+5

    x = map(f,z)
    
    return np.array(x)
```

### Error details
The first error is:
```bash/fortran/c
>               name = str(rhs.args[0])
E               AttributeError: 'PythonMap' object has no attribute 'args'
```

### To fix

The code should either be removed or modified to accept `list(map(f,z))`
